@extends('admin.layout')
@section('title','خرید و تأمین')
@section('heading','خرید و تأمین')
@section('subheading','شناسایی کمبود موجودی و آماده‌سازی درخواست خرید')
@section('content')
<div class="admin-page-kpis"><article><span>!</span><div><small>نیازمند تأمین</small><b>{{ fa_digits($products->count()) }}</b></div></article><article><span>⌂</span><div><small>تأمین‌کنندگان</small><b>{{ fa_digits($factories->count()) }}</b></div></article><article><span>▤</span><div><small>حداقل موجودی</small><b>{{ fa_digits($products->where('stock_kg','<',1000)->count()) }}</b></div></article><article><span>↗</span><div><small>درخواست‌های باز</small><b>۰</b></div></article></div>
<section class="admin-card"><div class="admin-card-head"><div><h3>لیست نیازهای خرید</h3><p>محصولاتی که موجودی آن‌ها پایین یا نیازمند استعلام هستند.</p></div><button class="btn btn-primary">+ درخواست خرید جدید</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>محصول</th><th>کارخانه پیشنهادی</th><th>موجودی فعلی</th><th>حداقل سفارش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($products as $p)<tr><td><div class="table-product"><img src="{{ site_asset($p->image) }}" alt=""><span><b>{{ $p->name }}</b><small>{{ $p->sku }}</small></span></div></td><td>{{ $p->factory?->name ?: 'انتخاب نشده' }}</td><td>{{ money_fa($p->stock_kg) }} کیلو</td><td>{{ fa_digits($p->min_order_tons) }} تن</td><td><span class="status-badge contacted">نیازمند بررسی</span></td><td><button class="icon-btn">ایجاد RFQ</button></td></tr>@empty<tr><td colspan="6" class="admin-empty">در حال حاضر کمبود موجودی ثبت نشده است.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-card" style="margin-top:16px"><div class="admin-card-head"><div><h3>فرآیند تأمین پیشنهادی</h3><p>از درخواست خرید تا رسید انبار</p></div></div><div class="order-status-bars"><div><span>۱. درخواست خرید</span><i><em style="width:100%"></em></i></div><div><span>۲. دریافت پیشنهاد کارخانه</span><i><em class="pending" style="width:60%"></em></i></div><div><span>۳. تأیید سفارش خرید</span><i><em class="pending" style="width:30%"></em></i></div><div><span>۴. رسید انبار و کنترل کیفیت</span><i><em class="failed" style="width:10%"></em></i></div></div></section>
@endsection
